//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export enum eAppRequestStatus { 
	Pending = 0, 
	Resolved = 1, 
	Rejected = 2, 
	Failed = 3, 
	None = 4
}
export enum eAppRequestType { 
	Add = 0, 
	Modify = 1, 
	Delete = 2
}
export enum eEntityStatus { 
	Active = 0, 
	Deleted = 1
}
