//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { eAppRequestType } from './enums';
import { eAppRequestStatus } from './enums';
import { eEntityStatus } from './enums';
import { eAdminRequestFor } from './enums';
import { eUserRole } from './enums';
import { eUserStatus } from './enums';

export interface IAppRequestDto<TDto>
{
	id: any;
	createdOn: any;
	requestType: eAppRequestType;
	requestStatus: eAppRequestStatus;
	entity: TDto;
	pendingRequestId: any;
	pendingRequest: IAppRequestDto<TDto>;
}
export interface IBaseDto
{
	id: any;
	entityStatus: eEntityStatus;
	createdOn: any;
}
export interface ICocktailDto extends IBaseDto
{
	name: string;
	excerpts: IExcerptDto[];
	ingredients: IIngredientDto[];
}
export interface IExcerptDto extends IBaseDto
{
	cocktailId: string;
	ingredientId: string;
	amount: number;
}
export interface IIngredientDto extends IBaseDto
{
	name: string;
	strength: number;
	excerpts: IExcerptDto[];
}
export interface IApiAdminRequestDto
{
	requestFor: eAdminRequestFor;
	args: string[];
}
export interface IApiBaseDto
{
}
export interface IAppStateDto extends IApiBaseDto
{
	processingInterval: number;
	syslogFiles: string[];
	logFile: number[];
}
export interface IAppUserDto
{
	id: any;
	role: eUserRole;
	status: eUserStatus;
	username: string;
	password: string;
	jwt: string;
}
